language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t vellumak/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vellumak/docker-react npm run test -- --coverage